services:
  catalog-service:
    build:
      context: .
      dockerfile: services/catalog/src/CatalogWebApi/Dockerfile
    container_name: catalog-service
    ports:
      - "5001:8080" # Map host port 5001 to container port 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - ConnectionStrings__DefaultConnection=Server=sqlserver-container,1433;Database=CatalogDb;User ID=sa;Password=P@ssw0rd2025;TrustServerCertificate=True
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      - LANG=en_US.UTF-8
    depends_on:
      - sqlserver-container
    networks:
      - app-network

  customer-service:
    build:
      context: .
      dockerfile: services/customer/src/CustomerWebApi/Dockerfile
    container_name: customer-service
    ports:
      - "5002:8080" # Map host port 5002 to container port 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - ConnectionStrings__DefaultConnection=Server=sqlserver-container,1433;Database=CustomerDb;User ID=sa;Password=P@ssw0rd2025;TrustServerCertificate=True
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      - LANG=en_US.UTF-8
    depends_on:
      - sqlserver-container
    networks:
      - app-network

  order-service:
    build:
      context: .
      dockerfile: services/order/src/OrderWebApi/Dockerfile
    container_name: order-service
    ports:
      - "5003:8080" # Map host port 5003 to container port 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - ConnectionStrings__DefaultConnection=Server=sqlserver-container,1433;Database=OrderDb;User ID=sa;Password=P@ssw0rd2025;TrustServerCertificate=True
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      - LANG=en_US.UTF-8
    depends_on:
      - sqlserver-container
    networks:
      - app-network

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: aspire-dashboard
    ports:
      - "18888:18888"
    networks:
      - app-network

  sqlserver-container:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd2025
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
