global:
  scrape_interval: 5s # How often to scrape targets by default.

scrape_configs:
  - job_name: "catalog-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["catalog-service:8080"]

  - job_name: "customer-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["customer-service:8080"]

  - job_name: "order-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["order-service:8080"]